# Araba Fiyatları (Car Prices)

🎯 Bu challenge’ın amacı, bir dataset hazırlamak ve şimdiye kadar öğrendiğiniz bazı feature selection tekniklerini uygulamaktır.

🚗 Arabalarla ilgili bir veri setiyle çalışıyoruz ve bir arabanın pahalı mı yoksa ucuz mu olduğunu tahmin etmek istiyoruz.

In [32]:
# Data manipulation
import numpy as np
import pandas as pd
# Data visualisation
import matplotlib.pyplot as plt
import seaborn as sns
# Sayısal bir özelliğin normal dağılım gösterip göstermediğini kontrol etme
from statsmodels.graphics.gofplots import qqplot


In [33]:
url = "https://d32aokrjazspmn.cloudfront.net/materials/ML_Cars_dataset.csv"

❓ CSV dosyasını `df` adlı bir veri çerçevesine yükleyin.

In [34]:
# Data load
df = pd.read_csv(url)
print(df.head())

  aspiration enginelocation carwidth  curbweight enginetype cylindernumber  \
0        std          front     64.1        2548       dohc           four   
1        std          front     64.1        2548       dohc           four   
2        std          front     65.5        2823       ohcv            six   
3        std          front      NaN        2337        ohc           four   
4        std          front     66.4        2824        ohc           five   

   stroke  peakrpm      price  
0    2.68     5000  expensive  
1    2.68     5000  expensive  
2    3.47     5000  expensive  
3    3.40     5500  expensive  
4    3.40     5500  expensive  


ℹ️ Dataset’in açıklaması [burada](https://drive.google.com/file/d/1ADSyjWfRGYqdXwCCN4PPC7PjQeMZ-ap-/view?usp=sharing ) mevcuttur. Egzersiz boyunca buna mutlaka referans verin.

## (1) Yinelenenler (Duplicates)

❓ Varsa, veri kümesinden yinelenenleri kaldırın. ❓

*Veri çerçevesini `df`* üzerine yazın.

In [35]:
duplicates = df[df.duplicated()]
duplicates

aspiration enginelocation carwidth  curbweight enginetype cylindernumber  \
1          std          front     64.1        2548       dohc           four   
11         std          front     64.8        2395        ohc           four   
22         std          front     63.8        1876        ohc           four   
26         std          front     63.8        1989        ohc           four   
45         std          front     63.6        1909        ohc           four   
56         std          front     65.7        2380      rotor            two   
62         std          front     66.5        2410        ohc           four   
116      turbo          front     68.4        3252          l           four   
119      turbo          front     63.8        2128        ohc           four   
120        std          front     63.8        1967        ohc           four   
121        std          front     63.8        1989        ohc           four   
123        std          front     64.6        2535        ohc           four   
127        std           rear       65        2756       ohcf            six   
159        std          front     64.4        2275        ohc           four   

     stroke  peakrpm      price  
1     2.680     5000  expensive  
11    2.800     5800  expensive  
22    3.230     5500      cheap  
26    3.230     5500      cheap  
45    3.110     5400      cheap  
56    3.255     6000  expensive  
62    3.390     4800      cheap  
116   3.520     4150  expensive  
119   3.390     5500      cheap  
120   3.230     5500      cheap  
121   3.230     5500      cheap  
123   3.460     5000      cheap  
127   2.900     5900  expensive  
159   3.350     4500      cheap

In [36]:
df = df.drop_duplicates()

## (2)  Eksik değerler (Missing values)

❓ Eksik değerleri bulun ve bunları ya `strategy = "most frequent"` (kategorik değişkenler için) ya da `strategy = "median"` (sayısal değişkenler için) kullanarak doldurun ❓

In [37]:
missing_values = df.isnull().sum()
print(missing_values)

aspiration         0
enginelocation    10
carwidth           2
curbweight         0
enginetype         0
cylindernumber     0
stroke             0
peakrpm            0
price              0
dtype: int64


### `carwidth`

<details>
    <summary> 💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>carwidth</code> sütununda eksik değerler birden fazla şekilde temsil edilmektedir. Bazıları <code>np.nan</code>, bazıları ise <code>*</code> olarak yer alır. Bunlar tespit edildikten sonra, eksik değerler verinin %30’undan daha azını oluşturduğu için medyan değerle doldurulabilir.
</details>

In [38]:
import pandas as pd

df['carwidth'] = pd.to_numeric(df['carwidth'], errors='coerce')

median_carwidth = df['carwidth'].median()
df['carwidth'] = df['carwidth'].fillna(median_carwidth)

print(df.isnull().sum())

aspiration         0
enginelocation    10
carwidth           0
curbweight         0
enginetype         0
cylindernumber     0
stroke             0
peakrpm            0
price              0
dtype: int64


### `enginelocation`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>enginelocation</code> kategorik bir feature olduğundan ve kategorilerin büyük çoğunluğu <code>front</code> olduğu için, en sık görülen değerle doldurun.
</details>

In [39]:
mode_enginelocation = df['enginelocation'].mode()[0]
df['enginelocation'] = df['enginelocation'].fillna(mode_enginelocation)

print(df.isnull().sum())

aspiration        0
enginelocation    0
carwidth          0
curbweight        0
enginetype        0
cylindernumber    0
stroke            0
peakrpm           0
price             0
dtype: int64


🧪 **Kodunu test et**

In [40]:
from nbresult import ChallengeResult

result = ChallengeResult('missing_values',
                         dataset = df)
result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/berkayturhan/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/berkayturhan/S16D2-S-Data-car-prices/tests
plugins: dash-3.3.0, anyio-4.8.0, typeguard-4.4.2
collecting ... collected 2 items

test_missing_values.py::TestMissing_values::test_carwidth PASSED         [ 50%]
test_missing_values.py::TestMissing_values::test_engine_location PASSED  [100%]

============================== 2 passed in 0.67s ===============================


💯 You can commit your code:

git add tests/missing_values.pickle

git commit -m 'Completed missing_values step'

git push origin master



## (3) Sayısal özelliklerin ölçeklendirilmesi (Scaling the numerical features)

In [41]:
# Hatırlatma olarak, DataFrame hakkında bazı bilgiler
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 0 to 204
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   aspiration      191 non-null    object 
 1   enginelocation  191 non-null    object 
 2   carwidth        191 non-null    float64
 3   curbweight      191 non-null    int64  
 4   enginetype      191 non-null    object 
 5   cylindernumber  191 non-null    object 
 6   stroke          191 non-null    float64
 7   peakrpm         191 non-null    int64  
 8   price           191 non-null    object 
dtypes: float64(2), int64(2), object(5)
memory usage: 14.9+ KB


In [42]:
# Ve işte ölçeklendirmemiz gereken veri kümesinin sayısal özellikleri
numerical_features = df.select_dtypes(exclude=['object']).columns
numerical_features

Index(['carwidth', 'curbweight', 'stroke', 'peakrpm'], dtype='object')

❓ **Soru: Sayısal feature’ların ölçeklenmesi** ❓

Sayısal feature’ları aykırı değerler (outliers) ve dağılımları açısından inceleyin ve duruma göre aşağıdaki yöntemleri uygulayın:
- Robust Scaler
- Standard Scaler

Dönüştürülmüş değerlerle orijinal sütunları değiştirin.

### `peakrpm` , `carwidth` , & `stroke`

<details>
    <summary>💡 <i>İpucu</i> </summary>

    
ℹ️ <code>peakrpm</code>, <code>carwidth</code> ve <code>stroke</code> normal dağılıma sahiptir ancak aynı zamanda bazı aykırı değerler (outlier) içerir. Bu nedenle `RobustScaler()` kullanılması tavsiye edilir.
</details>

In [43]:
from sklearn.preprocessing import RobustScaler

cols_to_scale = ['peakrpm', 'carwidth', 'stroke']

for col in cols_to_scale:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    
scaler = RobustScaler()

df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

print(df[cols_to_scale].head())

    peakrpm  carwidth    stroke
0 -0.142857 -0.518519 -2.033333
2 -0.142857  0.000000  0.600000
3  0.571429  0.000000  0.366667
4  0.571429  0.333333  0.366667
5  0.571429  0.296296  0.366667


### `curbweight`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>curbweight</code> normal bir dağılıma sahiptir ve aykırı değer (outlier) içermez. Bu nedenle Standard Scaler ile ölçeklenebilir.
</details>

In [44]:
from sklearn.preprocessing import StandardScaler

std_cols = ['curbweight']
std_scaler = StandardScaler()

df[std_cols] = std_scaler.fit_transform(df[std_cols])

print(df[std_cols].head())


   curbweight
0   -0.048068
2    0.476395
3   -0.450474
4    0.478302
5   -0.126260


🧪 **Kodunu test et**

In [45]:
from nbresult import ChallengeResult

result = ChallengeResult('scaling',
                         dataset = df
)

result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/berkayturhan/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/berkayturhan/S16D2-S-Data-car-prices/tests
plugins: dash-3.3.0, anyio-4.8.0, typeguard-4.4.2
collecting ... collected 4 items

test_scaling.py::TestScaling::test_carwidth PASSED                       [ 25%]
test_scaling.py::TestScaling::test_curbweight PASSED                     [ 50%]
test_scaling.py::TestScaling::test_peakrpm PASSED                        [ 75%]
test_scaling.py::TestScaling::test_stroke PASSED                         [100%]

============================== 4 passed in 0.38s ===============================


💯 You can commit your code:

git add tests/scaling.pickle

git commit -m 'Completed scaling step'

git push origin master



## (4) Kategorik özelliklerin kodlanması (Encoding the categorical features)

❓ **Soru: Kategorik değişkenlerin encode edilmesi** ❓

👇 Encode edilmesi gereken feature’ları inceleyin ve duruma göre aşağıdaki teknikleri uygulayın:

- One-hot encoding
- Manuel ordinal encoding

DataFrame içinde, orijinal feature’ları encode edilmiş versiyonlarıyla değiştirin.

### `aspiration` & `enginelocation`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>aspiration</code> ve <code>enginelocation</code> ikili (binary) kategorik feature’lardır.
</details>

In [46]:
print("Aspiration değerleri:", df['aspiration'].unique())
print("Engine Location değerleri:", df['enginelocation'].unique())

df['aspiration'] = df['aspiration'].map({'std': 0, 'turbo': 1})

df['enginelocation'] = df['enginelocation'].map({'front': 0, 'rear': 1})

print(df[['aspiration', 'enginelocation']].head())

Aspiration değerleri: ['std' 'turbo']
Engine Location değerleri: ['front' 'rear']
   aspiration  enginelocation
0           0               0
2           0               0
3           0               0
4           0               0
5           0               0


### `enginetype`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>enginetype</code> çok kategorili (multicategorical) bir feature’dır ve One-hot encoding uygulanmalıdır.
</details>

In [47]:
print("Enginetype değerleri:", df['enginetype'].unique())

df = pd.get_dummies(df, columns=['enginetype'], prefix='enginetype', dtype=int)

print(df.head())

Enginetype değerleri: ['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf' 'dohcv']
   aspiration  enginelocation  carwidth  curbweight cylindernumber    stroke  \
0           0               0 -0.518519   -0.048068           four -2.033333   
2           0               0  0.000000    0.476395            six  0.600000   
3           0               0  0.000000   -0.450474           four  0.366667   
4           0               0  0.333333    0.478302           five  0.366667   
5           0               0  0.296296   -0.126260           five  0.366667   

    peakrpm      price  enginetype_dohc  enginetype_dohcv  enginetype_l  \
0 -0.142857  expensive                1                 0             0   
2 -0.142857  expensive                0                 0             0   
3  0.571429  expensive                0                 0             0   
4  0.571429  expensive                0                 0             0   
5  0.571429  expensive                0                 0             0  

In [48]:
df.shape

(191, 15)

### `cylindernumber`

<details>
    <summary>💡 İpucu </summary>

ℹ️ <code>cylindernumber</code> sıralı (ordinal) bir feature’dır ve sayısal değerlere manuel olarak encode edilmelidir.

</details>

In [49]:
cylinder_mapping = {
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'eight': 8,
    'twelve': 12
}

df['cylindernumber'] = df['cylindernumber'].map(cylinder_mapping)

❓ Artık `cylindernumber`’ı 2 ile 12 arasında sayısal bir feature’a dönüştürdüğünüze göre, bunu ölçeklendirmeniz gerekiyor ❓

<br/>

<details>
    <summary>💡 İpucu </summary>

`cylindernumber`’ın mevcut dağılımına bakın ve kendinize şu soruları sorun:
- Ölçekleme, bir feature’ın dağılımını etkiler mi?
- Bu feature’ın dağılımına göre en uygun ölçekleme yöntemi hangisidir?
</details>

In [50]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

df[['cylindernumber']] = scaler.fit_transform(df[['cylindernumber']])

print(df[['cylindernumber']].head())

   cylindernumber
0             0.0
2             2.0
3             0.0
4             1.0
5             1.0


<details>
<summary><i>Ölçekleme ve encoding işlemlerinden sonra DataFrame’inizin nasıl görünmesi gerektiğine dair bir ekran görüntüsü aşağıdadır</i></summary>
    
    
<img src="https://wagon-public-datasets.s3.amazonaws.com/05-Machine-Learning/02-Prepare-the-dataset/car_price_after_scaling_and_encoding.png">    

</details>

In [51]:
print(df.head())

   aspiration  enginelocation  carwidth  curbweight  cylindernumber    stroke  \
0           0               0 -0.518519   -0.048068             0.0 -2.033333   
2           0               0  0.000000    0.476395             2.0  0.600000   
3           0               0  0.000000   -0.450474             0.0  0.366667   
4           0               0  0.333333    0.478302             1.0  0.366667   
5           0               0  0.296296   -0.126260             1.0  0.366667   

    peakrpm      price  enginetype_dohc  enginetype_dohcv  enginetype_l  \
0 -0.142857  expensive                1                 0             0   
2 -0.142857  expensive                0                 0             0   
3  0.571429  expensive                0                 0             0   
4  0.571429  expensive                0                 0             0   
5  0.571429  expensive                0                 0             0   

   enginetype_ohc  enginetype_ohcf  enginetype_ohcv  enginetyp

### `price`

👇 Hedef `price`ı kodlayın.

<details>
    <summary>💡 İpucu </summary>
    <br>
    ℹ️ <code>price</code> target değişkendir ve LabelEncoder ile encode edilmelidir.
</details>

In [56]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['price'] = le.fit_transform(df['price'])

print(df['price'].head())

0    1
2    1
3    1
4    1
5    1
Name: price, dtype: int64


🧪 **Kodunu test et**

In [57]:
from nbresult import ChallengeResult

result = ChallengeResult('encoding',
                         dataset = df)
result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/berkayturhan/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/berkayturhan/S16D2-S-Data-car-prices/tests
plugins: dash-3.3.0, anyio-4.8.0, typeguard-4.4.2
collecting ... collected 4 items

test_encoding.py::TestEncoding::test_aspiration PASSED                   [ 25%]
test_encoding.py::TestEncoding::test_enginelocation PASSED               [ 50%]
test_encoding.py::TestEncoding::test_enginetype PASSED                   [ 75%]
test_encoding.py::TestEncoding::test_price PASSED                        [100%]

============================== 4 passed in 0.60s ===============================


💯 You can commit your code:

git add tests/encoding.pickle

git commit -m 'Completed encoding step'

git push origin master



## (5) Temel Modelleme (Base Modelling)

👏 Veri kümesi ön işleme tabi tutuldu ve artık modele uyarlanmaya hazır. 

❓ **Soru: Bir classification modelini ilk kez değerlendirme** ❓

Ön işlenmiş bu dataset üzerinde bir `LogisticRegression` modeli için cross-validation çalıştırın ve elde edilen skoru `base_model_score` adlı değişkende saklayın.

In [58]:
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import cross_val_score

X = df.drop(columns=['price'])

y = df['price']

model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X, y, cv=5)

base_model_score = scores.mean()

print(f"Base Model Score (Accuracy): {base_model_score}")

Base Model Score (Accuracy): 0.8430499325236166


🧪 **Kodunu test et**

In [59]:
from nbresult import ChallengeResult

result = ChallengeResult('base_model',
                         score = base_model_score
)

result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/berkayturhan/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/berkayturhan/S16D2-S-Data-car-prices/tests
plugins: dash-3.3.0, anyio-4.8.0, typeguard-4.4.2
collecting ... collected 1 item

test_base_model.py::TestBase_model::test_base_model_score PASSED         [100%]

============================== 1 passed in 0.16s ===============================


💯 You can commit your code:

git add tests/base_model.pickle

git commit -m 'Completed base_model step'

git push origin master



## (6) Özellik Seçimi  (Feature Selection (with _Permutation Importance_))

👩🏻‍🏫 Bir feature’ın target’ı tahmin etmede gerçekten önemli olup olmadığını tespit etmenin güçlü bir yolu şudur:

1. Bir model çalıştırın ve skorunu ölçün  
2. Bu feature’ı karıştırın (shuffle edin), modeli tekrar çalıştırın ve skoru tekrar ölçün  
    - Eğer performans **belirgin şekilde düşerse**, bu feature önemlidir ve **çıkarılmamalıdır**
    - Eğer performans **çok fazla düşmezse**, bu feature **elenebilir**

❓ **Sorular** ❓

1. Modele en az bilgi katkısı sağlayan feature’ları tespit etmek için feature permutation uygulayın.
2. Model performansının belirgin şekilde düşmeye başladığını fark edene kadar zayıf feature’ları dataset’ten çıkarın.
3. Elde ettiğiniz yeni güçlü feature set’i ile yeni bir modeli cross-validation ile değerlendirin ve skorunu `strong_model_score` adlı değişkende saklayın.

In [70]:
from sklearn.inspection import permutation_importance

# Modeli tüm veri kümesi üzerinde eğitiyoruz
model = LogisticRegression(max_iter=1000)
model.fit(X, y)

permutation_score = permutation_importance(model, X, y, n_repeats=10, random_state=42)

# Özellik önemini alıyoruz
import pandas as pd
importance_df = pd.DataFrame({
    'feature': X.columns,
    'importance': permutation_score.importances_mean
}).sort_values(by='importance', ascending=False)

print("En önemli özellikler:\n", importance_df.head(10))

# Zayıf özellikleri kaldırıyoruz
threshold = 0.01
strong_features = importance_df[importance_df['importance'] > threshold]['feature'].tolist()

print(f"\nToplam {len(X.columns)} özellikten {len(strong_features)} tanesi seçildi.")

# Yeni güçlü veri seti
X_strong = X[strong_features]

scores = cross_val_score(model, X_strong, y, cv=5)
strong_model_score = scores.mean()

print(f"Strong Model Score: {strong_model_score}")

En önemli özellikler:
              feature  importance
3         curbweight    0.290576
2           carwidth    0.114660
5             stroke    0.029843
11   enginetype_ohcf    0.017277
10    enginetype_ohc    0.015183
6            peakrpm    0.014136
13  enginetype_rotor    0.011518
4     cylindernumber    0.009948
0         aspiration    0.009424
7    enginetype_dohc    0.005236

Toplam 14 özellikten 7 tanesi seçildi.
Strong Model Score: 0.874493927125506


🧪 **Kodunu test et**

In [71]:
from nbresult import ChallengeResult

result = ChallengeResult('strong_model',
                         score = strong_model_score
)

result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/berkayturhan/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/berkayturhan/S16D2-S-Data-car-prices/tests
plugins: dash-3.3.0, anyio-4.8.0, typeguard-4.4.2
collecting ... collected 1 item

test_strong_model.py::TestStrong_model::test_strong_model_score PASSED   [100%]

============================== 1 passed in 0.14s ===============================


💯 You can commit your code:

git add tests/strong_model.pickle

git commit -m 'Completed strong_model step'

git push origin master



## Bonus -  Verilerinizi sınıflandırma (Stratifying your data) ⚖️

💡 Veriyi training ve testing olarak bölerken, dataset’imizdeki kategorik değişkenlerin oranına dikkat etmemiz gerekir — ister target `y`’nin sınıfları olsun ister `X` içindeki kategorik bir feature olsun.

Aşağıda bir örneğe bakalım 👇

❓ Orijinal `X` ve `y` verinizi sklearn’in `train_test_split` fonksiyonunu kullanarak training ve testing olarak ayırın; karşılaştırılabilir sonuçlar elde etmek için `random_state=1` ve `test_size=0.3` kullanın.

In [76]:
# Verileri train ve test olarak ayırma
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_strong, y, test_size=0.3, random_state=1)

print("Train Setindeki Oranlar:\n", y_train.value_counts(normalize=True))
print("Test Setindeki Oranlar:\n", y_test.value_counts(normalize=True))

Train Setindeki Oranlar:
 price
1    0.503759
0    0.496241
Name: proportion, dtype: float64
Test Setindeki Oranlar:
 price
1    0.517241
0    0.482759
Name: proportion, dtype: float64


❓ Training dataset’inizde ve testing dataset’inizde `price` sınıfı **1** olan araçların oranını kontrol edin.

> _Ham `df` içinde bu orana baktığınızda, yaklaşık **%50 / %50** olması gerekir._

In [77]:
# Training dataset’inizde ve testing dataset’inizde `price` sınıfı **1** olan araçların oranını kontrol edelim.
print("Train setinde price sınıfı 1 oranı:", (y_train == 1).mean())
print("Test setinde price sınıfı 1 oranı:", (y_test == 1).mean())


Train setinde price sınıfı 1 oranı: 0.5037593984962406
Test setinde price sınıfı 1 oranı: 0.5172413793103449


☝️ Hâlâ yaklaşık olarak **%50 / %50** civarında olmalı.

***Peki random state’i değiştirirsek ne olur?***

❓ `random_state` değerlerini **1’den 10’a** kadar döngüye alın ve her seferinde training ve testing dataset’lerindeki `price` sınıfı **1** olan araçların oranını hesaplayın. ❓

In [79]:
for random_state in range(1, 11):
    X_train, X_test, y_train, y_test = train_test_split(X_strong, y, test_size=0.3, random_state=random_state)
    train_ratio = (y_train == 1).mean()
    test_ratio = (y_test == 1).mean()
    print(f"Random State {random_state}: Train price=1 oranı: {train_ratio:.4f}, Test price=1 oranı: {test_ratio:.4f}")

Random State 1: Train price=1 oranı: 0.5038, Test price=1 oranı: 0.5172
Random State 2: Train price=1 oranı: 0.4812, Test price=1 oranı: 0.5690
Random State 3: Train price=1 oranı: 0.5038, Test price=1 oranı: 0.5172
Random State 4: Train price=1 oranı: 0.5338, Test price=1 oranı: 0.4483
Random State 5: Train price=1 oranı: 0.5338, Test price=1 oranı: 0.4483
Random State 6: Train price=1 oranı: 0.4962, Test price=1 oranı: 0.5345
Random State 7: Train price=1 oranı: 0.5338, Test price=1 oranı: 0.4483
Random State 8: Train price=1 oranı: 0.4887, Test price=1 oranı: 0.5517
Random State 9: Train price=1 oranı: 0.5789, Test price=1 oranı: 0.3448
Random State 10: Train price=1 oranı: 0.4887, Test price=1 oranı: 0.5517


Her seferinde oranların değiştiğini, hatta bazen oldukça ciddi şekilde değiştiğini gözlemleyeceksiniz 😱! Bu durum model performansını etkileyebilir.

❓ `train_test_split(random_state=1)` kullanılarak eğitilen bir Logistic Regression modelinin test skorunu,  
`random_state=9` kullanılarak eğitilen modelin test skoru ile karşılaştırın ❓

Eğitimi training data üzerinde yapmayı ve skoru testing data üzerinde hesaplamayı unutmayın.

In [81]:
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(X_strong, y, test_size=0.3, random_state=1)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
score_1 = model.score(X_test, y_test)

X_train, X_test, y_train, y_test = train_test_split(X_strong, y, test_size=0.3, random_state=9)
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
score_9 = model.score(X_test, y_test)

print(f"Model Score with random_state=1: {score_1}")
print(f"Model Score with random_state=9: {score_9}")

Model Score with random_state=1: 0.9137931034482759
Model Score with random_state=9: 0.7931034482758621


👀 `random_state=9` ile çok daha düşük bir skor görmelisiniz; çünkü bu test setindeki sınıf **1** araçların oranı %34.5 iken, training setinde bu oran %57.9’a, hatta orijinal dataset’te yaklaşık %50’ye yakındır.

Bu durum oldukça önemlidir; çünkü dataset’te oluşan bu **rastlantısal dengesizlik**, yalnızca model performansını düşürmekle kalmaz, aynı zamanda eğitim veya değerlendirme sırasında “gerçekliği” de bozabilir 🧐

***Peki bu sorunu nasıl çözebiliriz? Tren seti ve test seti arasında sınıfların dağılımını nasıl aynı tutabiliriz? 🔧***

🎁 Neyse ki sklearn’de, estimator (yani model) bir classifier olduğunda ve target bir sınıf olduğunda, bu durum `cross_validate` tarafından otomatik olarak ele alınır. 📚 [**sklearn.model_selection.cross_validate**](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html) dokümantasyonunda `cv` parametresini inceleyin.

Çözüm, aşağıdakini kullanmaktır:

> 📚 [**Stratification (Katmanlama)**](https://scikit-learn.org/stable/modules/cross_validation.html#stratification)

### Hedefin tabakalaşması (Stratification of the target)

💡 ***Stratification*** tekniğini `train_test_split` içinde de kullanabiliriz.

❓ Bu kez **1’den 10’a** kadar olan `random_state` döngüsünü tekrar çalıştırın, ancak bu sefer holdout yöntemine ***`stratify=y`*** parametresini de ekleyin. ❓

In [82]:
for random_state in range(1, 11):
    X_train, X_test, y_train, y_test = train_test_split(X_strong, y, test_size=0.3, random_state=random_state, stratify=y)
    train_ratio = (y_train == 1).mean()
    test_ratio = (y_test == 1).mean()
    print(f"Random State {random_state}: Train price=1 oranı: {train_ratio:.4f}, Test price=1 oranı: {test_ratio:.4f}")

Random State 1: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 2: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 3: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 4: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 5: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 6: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 7: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 8: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 9: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000
Random State 10: Train price=1 oranı: 0.5113, Test price=1 oranı: 0.5000


👀 Random state değişse bile, training ve testing verilerindeki sınıf oranları, orijinal `y` içindeki oranlarla aynı tutulur. İşte _stratification_ (katmanlama) tam olarak budur.

`train_test_split` fonksiyonunu `stratify` parametresiyle kullandığımızda, training ve testing verileri arasında **bir feature’ın oranlarını da koruyabiliriz**. Bu, özellikle aşağıdaki durumlarda son derece önemlidir:

- Churn tahmininde erkek ve kadın müşteri oranlarını korumak 🙋‍♂️ 🙋
- Ev fiyatlarını tahmin ederken büyük ve küçük evlerin oranlarını korumak 🏠 🏰
- Bir sonraki ürünü önerirken 1–5 arası review score dağılımını (multiclass!) korumak 🛍️
- vb.

Örneğin, bizim dataset’imizde `aspiration` feature’ının training ve testing verilerinde aynı oranda kalmasını istiyorsak, şu şekilde yazabiliriz:

`train_test_split(X, y, test_size=0.3, stratify=X.aspiration)`

---

Gördüğümüz gibi, **`cross_validate` [target değişkeni otomatik olarak stratify edebilir](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html#:~:text=For%20int/None%20inputs%2C%20if%20the%20estimator%20is%20a%20classifier%20and%20y%20is%20either%20binary%20or%20multiclass%2C%20StratifiedKFold%20is%20used.)**, ancak **feature’lar için bunu yapmaz** 🤔 Bunun için biraz ekstra çalışmaya ihtiyacımız var.

Bunun için `StratifiedKFold` kullanmamız gerekiyor 🔬

### Tabakalaşma (Stratification - generalized)

📚 [**StratifiedKFold**](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html), veriyi `K` parçaya bölerken belirli sütunlar (feature veya target) üzerinden stratification yapmamıza olanak tanır.

Bu sayede, ilgilendiğimiz kategorik feature’ların oranlarını koruyarak manuel bir cross-validation yapabiliriz — bunu ikili (binary) `aspiration` feature’ı ile deneyelim:

In [83]:
from sklearn.model_selection import StratifiedKFold

# Veriyi 5 fold’a bölecek bir stratified k-fold oluşturma
skf = StratifiedKFold(n_splits=5)
scores = []

# .split() metodu bir iterator oluşturur; 'X.aspiration' stratify edeceğimiz feature’dır
for train_indices, test_indices in skf.split(X, X.aspiration):

    # 'train_indices' ve 'test_indices', orantılı bölünmeler üreten indeks listeleridir
    X_train, X_test = X.iloc[train_indices], X.iloc[test_indices]
    y_train, y_test = y.iloc[train_indices], y.iloc[test_indices]

    # modeli başlatma ve eğitme
    model = LogisticRegression()
    model.fit(X_train, y_train)

    # en sonunda 5 fold’un ortalamasını almak için skoru listeye ekleme
    scores.append(model.score(X_test, y_test))

np.array(scores).mean()

0.8585695006747638

📚 [**StratifiedKFold**](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html), veriyi `K` parçaya bölerken belirli sütunlar (feature veya target) üzerinden stratification yapmamıza olanak tanır.

Bu sayede, ilgilendiğimiz kategorik feature’ların oranlarını koruyarak manuel bir cross-validation yapabiliriz — bunu ikili (binary) `aspiration` feature’ı ile deneyelim:


🏁 Tebrikler! Tüm veri setini hazırladınız, özellik seçimi yaptınız ve hatta tabakalaşma hakkında bilgi edindiniz 💪.

💾 Not defterinizi git add/commit/push yapmayı unutmayın...

🚀 ... ve bir sonraki challenge'a geçin!